App_OL2022/Controllers/CourseTypeController.cs
using mysqltest.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mysqltest.Controllers
{
    public class CourseTypeController : Controller
    {
        owldbEntities01 owldb = new owldbEntities01();
        RoleSearching rs = new RoleSearching();
        // GET: Module
        public ActionResult Index(int? page)
        {

            if (Request.IsAuthenticated)
            {
                ViewBag.role = rs.GetRole(this.HttpContext.User.Identity.Name);
            }

            var pageNumber = page ?? 1;
            var pageSize = 10;
            var query = owldb.course_type.OrderBy(a => a.name).ToPagedList(pageNumber, pageSize);

            return View(query);
        }

        // GET: Module/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Module/Create
        [HttpPost]
        public ActionResult Create(course_type ct)
        {
            var query = owldb.course_type.Where(x => x.name == ct.name).FirstOrDefault();

            try
            {
                if (query==null)
                {
                    owldb.course_type.Add(ct);
                    owldb.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "* Nombre de Tipo de Curso Existente.";
                    return View(ct);
                }
                
            }
            catch (DbEntityValidationException dbEx)
            {
                return View();
            }
        }

        // GET: Module/Edit/5
        public ActionResult Edit(int id)
        {
            course_type ct = new course_type();
            ct = owldb.course_type.Where(x => x.course_type_id == id).FirstOrDefault();

            return View(ct);
        }

        // POST: Module/Edit/5
        [HttpPost]
        public ActionResult Edit(course_type ct)
        {
            var query = owldb.course_type.Where(x => x.course_type_id != ct.course_type_id && x.name == ct.name).FirstOrDefault();

            try
            {
                if (query == null)
                {
                    course_type courseT = owldb.course_type.Single(q => q.course_type_id == ct.course_type_id);
                    courseT.name = ct.name;

                    owldb.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "* Nombre de Tipo de Curso Existente.";
                    return View();
                }
                
            }
            catch (DbEntityValidationException dbEx)
            {
                return View();
            }
        }

        // GET: Module/Delete/5
        public ActionResult Delete(int id, string q)
        {
            var query = owldb.course_type.Where(a => a.course_type_id == id).FirstOrDefault();
            course_type ct = new course_type();
            ct.course_type_id = query.course_type_id; 
            ct.name = query.name;

            return View(ct);
        }

        // POST: Module/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var query = owldb.course_type.Where(a => a.course_type_id == id).FirstOrDefault();
                owldb.course_type.Remove(query);
                owldb.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

App_OL2022/Views/CourseType/Create.cshtml
@model mysqltest.Models.course_type

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Crear</title>
    <link href="~/css/homeCss/home.css" rel="stylesheet" />
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link href="~/css/styleguide.css" rel="stylesheet" />
    <link href="~/css/globals.css" rel="stylesheet" />
    <link href="~/css/css-boots/bootstrap.css" rel="stylesheet" />
</head>
<body style="background-color: #ffffff;">
    <!-- header -->
    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                  
                </div>
            </div>
        </div>
    </div>

    </header>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="row justify-content-center" style="margin-top: 3%;">


    <div class="col-lg-5 px-lg-3 pt-4 card" style="style= border: 1xp; border-color: #667b68;">
        <div class="container">

            <div class="form-horizontal">
                <h2 style="text-align: center;">Crear Nuevo Tipo de Curso</h2>

                <p style="color: red;">@ViewBag.Error</p>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <h3 class="control-label col-md-auto">Tipo de Curso</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @style = "color: #EAD1C5" })
                    </div>
                </div>

                <div class="form-group pb-3">
                    <div class="col-md-offset-2 col-md-10" style="margin-top:7%">
                        <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Index","CourseType")">Regresar</a>
                        <input id="CreartipoCurso" type="submit" value="Crear" class="btn btn-outline-dark" />
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

    }

</body>
</html>

App_OL2022/Views/CourseType/Delete.cshtml
@model mysqltest.Models.course_type

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Eliminar</title>
    <link href="~/css/homeCss/home.css" rel="stylesheet" />
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link href="~/css/styleguide.css" rel="stylesheet" />
    <link href="~/css/globals.css" rel="stylesheet" />
    <link href="~/css/css-boots/bootstrap.css" rel="stylesheet" />
</head>
<body style="background-color: #ffffff;">

    <div class=" row justify-content-center">
        <div class=" col-lg-8 crud-general2 screen ">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.course_type_id)


        <div class="row justify-content-center" style="margin-top: 3%;">


            <div class="col-lg-8 px-lg-3 pt-4 card" style=" border: ; border-color: #667b68;">
                <div class="container">


                    <div class="form-horizontal">
                        <h2 style="text-align: center;">Eliminar tipo curso</h2>
                    </div>
                    <hr />

                    <table class="table table-striped table-bordered " style="background-color: #D2DCCD;  margin-top: 4% ">
                        <thead class="thead-light">
                            <tr class="text-center">
                                <th>Identificador</th>
                                <th>Tipo de Curso</th>
                            </tr>
                        </thead>

                        <tr class="text-center">
                            <td>
                                @Html.DisplayFor(model => model.course_type_id, new { @class = "form-control" })
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.name, new { @class = "form-control" })
                            </td>
                        </tr>

                    </table>
                    <div class="form-group pb-3" style="margin-top:7%">
                        <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Index","CourseType")">Regresar</a>
                        <input style=" margin-left: " type="submit" value="Eliminar" class="btn btn-outline-danger" />
                    </div>
                </div>

            </div>
        </div>


    }


</body>
</html>

App_OL2022/Views/CourseType/Edit.cshtml
@model mysqltest.Models.course_type

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Editar</title>
    <link href="~/css/homeCss/home.css" rel="stylesheet" />
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link href="~/css/styleguide.css" rel="stylesheet" />
    <link href="~/css/globals.css" rel="stylesheet" />
    <link href="~/css/css-boots/bootstrap.css" rel="stylesheet" />
</head>
<body style="background-color: #ffffff;">
    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                   
                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div  class="row justify-content-center" style="margin-top: 3%;">

            <div class="col-lg-6 px-lg-6 pt-4 card" style="style= border: 1xp; border-color: #667b68;">
                <div class="container">

                    <div class="form-horizontal">
                        <h2 style="text-align:center;">Edici&oacute;n de Tipo de Curso</h2>

                        <p style="color: red;">@ViewBag.Error</p>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger text-dark" })
                        @Html.HiddenFor(model => model.course_type_id)

                        <div class="form-group">
                            <h3 class="control-label col-md-12">Tipo de Curso</h3>
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control text-dark" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @style = "color: #EAD1C5" })
                            </div>
                        </div>

                        <div class="form-group pb-3">
                            <div class="col-md-offset-2 col-md-10" style="margin-top:7%">
                                <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Index","CourseType")">Regresar</a>
                                <input type="submit" value="Editar" class="btn btn-outline-dark" />
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    }

</body>
</html>

App_OL2022/Views/CourseType/Index.cshtml
@*@model IEnumerable<mysqltest.Models.course_type>*@

@using mysqltest.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<course_type>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Tipos de cursos</title>
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/css/Cruds/crud-general2.css" />
    <link rel="stylesheet" type="text/css" href="~/css/styleguide.css" />
    <link rel="stylesheet" type="text/css" href="~/css/globals.css" />
    <link rel="stylesheet" type="text/css" href="~/css/css-boots/bootstrap.css" />
    <link href="~/css/Pagination.css" rel="stylesheet" />


    <style>
        table.dataTable thead .sorting:after,
        table.dataTable thead .sorting:before,
        table.dataTable thead .sorting_asc:after,
        table.dataTable thead .sorting_asc:before,
        table.dataTable thead .sorting_asc_disabled:after,
        table.dataTable thead .sorting_asc_disabled:before,
        table.dataTable thead .sorting_desc:after,
        table.dataTable thead .sorting_desc:before,
        table.dataTable thead .sorting_desc_disabled:after,
        table.dataTable thead .sorting_desc_disabled:before {
            bottom: .5em;
        }

        .myclass:hover {
            color: white;
        }
    </style>


    <script>
        $(document).ready(function () {
            $('#dtBasicExample').DataTable();
            $('.dataTables_length').addClass('bs-select');
        });

        $(document).ready(function () {
            $('#dtBasicExample').DataTable({
                "searching": false // false to disable search (or any other option)
            });
            $('.dataTables_length').addClass('bs-select');
        });
    </script>
    <script>
        function myFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("search");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
</head>

<body style="margin: 0; background: #ffffff">
    <input type="hidden" id="anPageName" name="page" value="crud-general2" />
    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                    <a href="@Url.Action("Index", "Admin")">
                        <div class="inicio">Administraci&oacute;n</div>
                    </a>
                    <a href="@Url.Action("Index","Courses")">
                        <div class="registrarse">Cursos</div>
                    </a>
                    <a href="@Url.Action("Index","Schedule")">
                        <div class="iniciar-sesin">Horarios</div>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid" style="margin-top:5%;">

        <h2 style="color: #677C78;" class="text-center">ADMINISTRACIÓN DE TIPOS DE CURSO</h2>

        <div class="row g-0" style="margin-top:2%; margin-left:4%;">

            <div class="col-md-9">
                <a id="VolvertipoCurso" class="btn btn-outline-dark" href="@Url.Action("Index", "Admin")"><span>Regresar</span></a>
                @if (ViewBag.role == 1)
                {
                    <a id="CreartipoCurso" class="main_nav_item btn btn-outline-dark" href="@Url.Action("Create","CourseType")"><span>Crear nuevo tipo de curso</span></a>
                }
            </div>

            <div class="col-md-3">

                <form class="form-inline my-2 my-lg-0 " style="margin: 10%; padding: 5%;">
                    <input class="form-control mr-sm-2 text-dark" type="text" id="search" placeholder="Buscar" onkeyup="myFunction()">

                </form>
            </div>

        </div>


        <div style=" width: 95%; margin-left: 3%;">
            <table class="table table-hover" id="myTable">
                <thead class="table-dark">
                    <tr class="text-center">
                        <th>Identificador</th>
                        <th>Tipo de Curso</th>
                        <th colspan="3">
                            Acciones
                        </th>

                    </tr>
                </thead>

                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td>
                            @Html.DisplayFor(modelItem => item.course_type_id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td>
                            <a id="" class="btn btn-outline-dark" href="@Url.Action("Edit","CourseType", new { id = item.course_type_id })"><span>Editar</span></a>
                        </td>
                        <td>
                            <a id"Crearhorario" class="btn btn-outline-dark" href="@Url.Action("Delete","CourseType", new { id = item.course_type_id })"><span>Eliminar</span></a>
                        </td>
                    </tr>
                }

            </table>
        </div>

        <div class="row g-0" style="padding: 1%;">
            <div class="col-md-6">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
            </div>
            <div class="col-md-6">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
            </div>
        </div>

    </div>

    </body>
</html>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>