App_OL2022/Controllers/TestTypeController.cs
using mysqltest.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mysqltest.Controllers
{
    public class TestTypeController : Controller
    {
        owldbEntities01 owldb = new owldbEntities01();
        RoleSearching rs = new RoleSearching();
        // GET: Module
        public ActionResult Index(int? page)
        {

            if (Request.IsAuthenticated)
            {
                ViewBag.role = rs.GetRole(this.HttpContext.User.Identity.Name);
            }

            var pageNumber = page ?? 1;
            var pageSize = 10;
            var query = owldb.test_type.OrderBy(a => a.name).ToPagedList(pageNumber, pageSize);

            return View(query);
        }

        // GET: Module/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Module/Create
        [HttpPost]
        public ActionResult Create(test_type tt)
        {
            var query = owldb.test_type.Where(x => x.name == tt.name).FirstOrDefault();

            try
            {
                if (query==null)
                {
                    owldb.test_type.Add(tt);
                    owldb.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "* Tipo de Prueba Existente.";
                    return View();
                }
            }
            catch (DbEntityValidationException dbEx)
            {
                return View();
            }
        }


        // GET: Module/Edit/5
        public ActionResult Edit(int id)
        {
            test_type ct = new test_type();
            ct = owldb.test_type.Where(x => x.test_type_id == id).FirstOrDefault();

            return View(ct);
        }

        // POST: Module/Edit/5
        [HttpPost]
        public ActionResult Edit(test_type tt)
        {
            var query = owldb.test_type.Where(x => x.test_type_id != tt.test_type_id && x.name == tt.name).FirstOrDefault();

            try
            {
                if (query==null)
                {
                    test_type typeT = owldb.test_type.Single(q => q.test_type_id == tt.test_type_id);
                    typeT.name = tt.name;

                    owldb.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "* Tipo de Prueba Existente.";
                    return View();
                }
                
            }
            catch (DbEntityValidationException dbEx)
            {
                return View();
            }
        }

        // GET: Module/Delete/5
        public ActionResult Delete(int id, string q)
        {
            var query = owldb.test_type.Where(a => a.test_type_id == id).FirstOrDefault();
            test_type ct = new test_type();
            ct.test_type_id = query.test_type_id;
            ct.name = query.name;

            return View(ct);
        }

        // POST: Module/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var query = owldb.test_type.Where(a => a.test_type_id == id).FirstOrDefault();
                owldb.test_type.Remove(query);
                owldb.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

App_OL2022/Views/TestType/Create.cshtml
@model mysqltest.Models.test_type

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Crear</title>
    <link href="~/css/homeCss/home.css" rel="stylesheet" />
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link href="~/css/styleguide.css" rel="stylesheet" />
    <link href="~/css/globals.css" rel="stylesheet" />
    <link href="~/css/css-boots/bootstrap.css" rel="stylesheet" />
</head>
<body style="background-color: #ffffff;">

    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="row justify-content-center" style="margin-top: 3%;">

            <div class="col-lg-5 px-lg-3 pt-4 card" style="style= border: 1xp; border-color: #667b68;">
                <div class="container">

                    <div class="form-horizontal">
                        <h2 style="color: ;">Crear Nuevo Tipo de Prueba</h2>
                        <p style="color: red;">@ViewBag.Error</p>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @style = "color: #EAD1C5" })
                        <div class="form-group">
                            <h3 class="control-label col-md-auto">Tipo de Prueba</h3>
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @style = "color: #EAD1C5" })
                            </div>
                        </div>

                        <div class="form-group pb-3">
                            <div class="col-md-offset-2 col-md-10" style="margin-top:7%">
                                <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Index","TestType")">Regresar </a>
                                <input type="submit" value="Crear" class="main_nav_item btn btn-outline-dark" />

                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    }

</body>
</html>

App_OL2022/Views/TestType/Delete.cshtml
@model mysqltest.Models.test_type

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Eliminar</title>
    <link href="~/css/homeCss/home.css" rel="stylesheet" />
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link href="~/css/styleguide.css" rel="stylesheet" />
    <link href="~/css/globals.css" rel="stylesheet" />
    <link href="~/css/css-boots/bootstrap.css" rel="stylesheet" />

</head>
<body style="background-color: #ffffff;">
    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.test_type_id)

        <div class="form-actions no-color">

            <div class="row justify-content-center" style="margin-top: 3%;">

                <div class="col-lg-3 px-lg-3 pt-4 card" style="style= border: 1xp; border-color: #667b68;">
                    <div class="container">


                        <div class="form-horizontal">
                            <h2 style="color: ;">Eliminar tipo de prueba</h2>
                        </div>
                        <hr />

                        <table class="table table-striped table-bordered" style="background-color: #D2DCCD; margin-top: 4%">
                            <thead class="thead-light">
                                <tr class="text-center">
                                    <th>Identificador</th>
                                    <th>Tipo de Prueba</th>
                                </tr>
                            </thead>

                            <tr class="text-center">
                                <td>
                                    @Html.DisplayFor(model => model.test_type_id, new { @class = "form-control" })
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.name, new { @class = "form-control" })
                                </td>
                            </tr>

                        </table>

                        <div class="form-group pb-3" style="margin-top:7%">
                            <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Index","TestType")">Regresar</a>
                            <input style=" margin-left: " type="submit" value="Eliminar" class="btn btn-outline-danger" />
                        </div>


                    </div>

                </div>
            </div>

        </div>
    }


</body>
</html>

App_OL2022/Views/TestType/Edit.cshtml
@model mysqltest.Models.test_type

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Editar</title>
    <link href="~/css/homeCss/home.css" rel="stylesheet" />
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link href="~/css/styleguide.css" rel="stylesheet" />
    <link href="~/css/globals.css" rel="stylesheet" />
    <link href="~/css/css-boots/bootstrap.css" rel="stylesheet" />
</head>
<body style="background-color: #ffffff;">

    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="row justify-content-center" style="margin-top: 3%;">

            <div class="col-lg-3 px-lg-3 pt-4 card" style="style= border: 1xp; border-color: #667b68;">
                <div class="container">

                    <div class="form-horizontal">
                        <h2 style="color: ;">Editar tipo de prueba</h2>
                        <p style="color: red;">@ViewBag.Error</p>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.test_type_id)

                        <div class="form-group">
                            <h3 class="control-label col-md-auto">Tipo de Curso</h3>
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @style = "color: #EAD1C5" })
                            </div>
                        </div>

                        <div class="form-group pb-3">
                            <div class="col-md-offset-2 col-md-10" style="margin-top:7%">
                                <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Index","TestType")">Regresar</a>
                                <input type="submit" value="Editar" class="btn btn-outline-dark" />
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    }

</body>
</html>

App_OL2022/Views/TestType/Index.cshtml
@*@model IEnumerable<mysqltest.Models.test_type>*@

@using mysqltest.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<test_type>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Tipos de Prueba</title>
    <link rel="stylesheet" type="text/css" href="~/css/Cruds/crud-general2.css" />
    <link rel="stylesheet" type="text/css" href="~/css/styleguide.css" />
    <link rel="stylesheet" type="text/css" href="~/css/globals.css" />
    <link href="~/css/Pagination.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/css/css-boots/bootstrap.css" />

    <style>
        table.dataTable thead .sorting:after,
        table.dataTable thead .sorting:before,
        table.dataTable thead .sorting_asc:after,
        table.dataTable thead .sorting_asc:before,
        table.dataTable thead .sorting_asc_disabled:after,
        table.dataTable thead .sorting_asc_disabled:before,
        table.dataTable thead .sorting_desc:after,
        table.dataTable thead .sorting_desc:before,
        table.dataTable thead .sorting_desc_disabled:after,
        table.dataTable thead .sorting_desc_disabled:before {
            bottom: .5em;
        }

        .myclass:hover {
            color: white;
        }
    </style>


    <script>
        $(document).ready(function () {
            $('#dtBasicExample').DataTable();
            $('.dataTables_length').addClass('bs-select');
        });

        $(document).ready(function () {
            $('#dtBasicExample').DataTable({
                "searching": false // false to disable search (or any other option)
            });
            $('.dataTables_length').addClass('bs-select');
        });
    </script>

    <script>
        function myFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("search");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>

</head>
<body style="margin: 0; background: #ffffff">
    <input type="hidden" id="anPageName" name="page" value="crud-general2" />
    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">
                    <a href="@Url.Action("Index", "Admin")">
                        <div class="inicio">Administraci&oacute;n</div>
                    </a>
                    <a href="@Url.Action("Index","VirtualTest")">
                        <div class="registrarse">Pruebas</div>
                    </a>
                    <a href="@Url.Action("Index","Questions")">
                        <div class="iniciar-sesin">Preguntas</div>
                    </a>
                </div>
            </div>
        </div>
    </div>


        <h2 style="color: #677C78; margin-top: 2%;" class="text-center">ADMINISTRACIÓN DE TIPOS DE PRUEBA</h2>

        <div class="row g-0" style="margin-top:2%; margin-left:4%;">

            <div class="col-md-9">
                <a class="btn btn-outline-dark" href="@Url.Action("Index","VirtualTest")">Volver a Pruebas Virtuales</a>
                @if (ViewBag.role == 1)
                {
                    <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Create","TestType")">Crear Nuevo Tipo de Prueba</a>
                }
            </div>

            <div class="col-md-3">

                <form class="form-inline my-2 my-lg-0 " style="margin: 10%; padding: 5%;">
                    <input class="form-control mr-sm-2 text-dark" type="text" id="search" placeholder="Buscar" onkeyup="myFunction()">

                </form>
            </div>

        </div>

        <div style=" width: 95%; margin-left: 3%;">

            <table class="table table-hover" id="myTable">
                <thead class="table-dark">
                    <tr class="text-center">
                        <th>Identificador</th>
                        <th>Tipo de Prueba</th>
                        <th colspan="2">
                            Acciones
                        </th>

                    </tr>
                </thead>

                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td>
                            @Html.DisplayFor(modelItem => item.test_type_id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td>
                            <a class="btn btn-outline-dark" href="@Url.Action("Edit","TestType", new { id = item.test_type_id })">Editar</a>
                        </td>
                        <td>
                            <a class="btn btn-outline-dark" href="@Url.Action("Delete","TestType", new { id = item.test_type_id })">Eliminar</a>
                        </td>
                    </tr>
                }

            </table>
        </div>

        <div class="row g-0" style="padding: 1%;">
            <div class="col-md-6">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
            </div>
            <div class="col-md-6">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
            </div>
        </div>



</body>
</html>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>