App_OL2022/Controllers/VirtualTestController.cs
using mysqltest.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mysqltest.Controllers
{
    public class VirtualTestController : Controller
    {
        owldbEntities01 owldb = new owldbEntities01();
        RoleSearching rs = new RoleSearching();

        // GET: Module
        public ActionResult Index(int? page)
        {
            if (Request.IsAuthenticated)
            {
                ViewBag.role = rs.GetRole(this.HttpContext.User.Identity.Name);
            }

            var pageNumber = page ?? 1;
            var pageSize = 10;
            var query = owldb.virtual_tests.OrderBy(a => a.virtual_test_id).ToPagedList(pageNumber, pageSize);

            return View(query);
        }

        public ActionResult GetInfo(int id)
        {
            var query = owldb.question_vt.Where(x => x.virtual_tests.virtual_test_id == id).ToList();

            var query2 = owldb.virtual_tests.Where(y => y.virtual_test_id == id).FirstOrDefault();

            ViewBag.prueba = query2.name;
            return View(query);
        }

        // GET: Module/Create
        public ActionResult Create()
        {
            ViewBag.testType = owldb.test_type.Select(x => x);
            return View();
        }

        // POST: Module/Create
        [HttpPost]
        public ActionResult Create(virtual_tests vt)
        {
            var query = owldb.virtual_tests.Where(x => x.name == vt.name).FirstOrDefault();

            try
            {
                if (query==null)
                {
                    owldb.virtual_tests.Add(vt);
                    owldb.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "* Nombre de Prueba Virtual Existente.";
                    ViewBag.testType = owldb.test_type.Select(x => x);
                    return View();
                }
                
            }
            catch (DbEntityValidationException dbEx)
            {
                ViewBag.testType = owldb.test_type.Select(x => x);
                return View();
            }
        }

        // GET: Module/Edit/5
        public ActionResult Edit(int id)
        {
            virtual_tests vt = new virtual_tests();
            vt = owldb.virtual_tests.Where(x => x.virtual_test_id == id).FirstOrDefault();

            ViewBag.testType = owldb.test_type.Select(y => y);

            return View(vt);
        }

        // POST: Module/Edit/5
        [HttpPost]
        public ActionResult Edit(virtual_tests vt)
        {
            var query = owldb.virtual_tests.Where(x => x.virtual_test_id != vt.virtual_test_id && x.name == vt.name).FirstOrDefault();

            try
            {
                if (query == null)
                {
                    virtual_tests virtualT = owldb.virtual_tests.Single(q => q.virtual_test_id == vt.virtual_test_id);
                    virtualT.name = vt.name;
                    virtualT.instructions = vt.instructions;
                    virtualT.duration = vt.duration;
                    virtualT.type = vt.type;

                    owldb.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "* Nombre de Prueba Virtual Existente.";
                    ViewBag.testType = owldb.test_type.Select(y => y);
                    return View();
                }

            }
            catch (DbEntityValidationException dbEx)
            {
                ViewBag.testType = owldb.test_type.Select(y => y);
                return View();
            }
        }

        // GET: Module/Delete/5
        public ActionResult Delete(int id, string q)
        {
            var query = owldb.virtual_tests.Where(a => a.virtual_test_id == id).FirstOrDefault();
            virtual_tests vt = new virtual_tests();
            vt.name = query.name;
            vt.duration = query.duration;
            vt.instructions = query.instructions;

            var query2 = owldb.test_type.Where(x => x.test_type_id == query.type).FirstOrDefault();

            ViewBag.testType = query2.name;

            return View(vt);
        }

        // POST: Module/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var q = owldb.module_vt.Where(a => a.virtual_test == id).FirstOrDefault();
                var query = owldb.virtual_tests.Where(a => a.virtual_test_id == id).FirstOrDefault();

                if (q != null)
                {
                    ViewBag.message = "No se puede Eliminar la prueba ya que se encuentra asignada a un Módulo";
                    return View(query);
                }
                else
                {
                    owldb.virtual_tests.Remove(query);
                    owldb.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch(Exception e)
            {
                return View();
            }
        }
    }
}

App_OL2022/Views/VirtualTest/Create.cshtml
@model mysqltest.Models.virtual_tests

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Crear Curso</title>
    <link href="~/css/homeCss/home.css" rel="stylesheet" />
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link href="~/css/styleguide.css" rel="stylesheet" />
    <link href="~/css/globals.css" rel="stylesheet" />
    <link href="~/css/css-boots/bootstrap.css" rel="stylesheet" />
</head>
<body style="background-color: #ffffff;">

    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="row justify-content-center" style="margin-top: 3%;">

            <div class="col-lg-5 px-lg-3 pt-4 card" style="style= border: 1xp; border-color: #667b68;">

                <div class="container">

                    <div class="form-horizontal">

                        <h2 style="color: ;">Crear Nueva Prueba</h2>

                        <p style="color: red;">@ViewBag.Error</p>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <h3 class="control-label col-md-auto">Nombre</h3>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control text-dark" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @style = "color: #EAD1C5" })
                            </div>
                        </div>

                        <div class="form-group">
                            <h3 class="control-label col-md-auto">Duración</h3>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.duration, new { htmlAttributes = new { @class = "form-control text-dark" } })
                                @Html.ValidationMessageFor(model => model.duration, "", new { @style = "color: #EAD1C5" })
                            </div>
                        </div>

                        <div class="form-group">
                            <h3 class="control-label col-md-auto">Instrucciones</h3>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.instructions, new { htmlAttributes = new { @class = "form-control text-dark" } })
                                @Html.ValidationMessageFor(model => model.instructions, "", new { @style = "color: #EAD1C5" })
                            </div>
                        </div>

                        <div class="form-group">
                            <h3 class="control-label col-md-auto">Tipo</h3>
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.type, new SelectList(ViewBag.testType, "test_type_id", "name"), new { @class = "form-control text-dark" })
                                @Html.ValidationMessageFor(model => model.type, "", new { @style = "color: #EAD1C5" })
                            </div>
                        </div>

                        <div class="form-group pb-3">
                            <div class="col-md-offset-2 col-md-auto" style="margin-top:7%">
                                <a class=" btn btn-outline-dark" href="@Url.Action("Index","VirtualTest")">Regresar </a>
                                <input type="submit" value="Crear" class=" btn btn-outline-dark" />

                            </div>
                        </div>



                    </div>

                </div>

            </div>
        </div>
    }

</body>
</html>

App_OL2022/Views/VirtualTest/Delete.cshtml
@model mysqltest.Models.virtual_tests

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Eliminar</title>
    <link href="~/css/homeCss/home.css" rel="stylesheet" />
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link href="~/css/styleguide.css" rel="stylesheet" />
    <link href="~/css/globals.css" rel="stylesheet" />
    <link href="~/css/css-boots/bootstrap.css" rel="stylesheet" />
</head>

<body style="background-color: #ffffff;">

    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.virtual_test_id)

        <div class="form-actions no-color">
            <h3 class="text-danger" style="margin:5px 0 0 10px;"> @ViewBag.message</h3>

            <div class="row justify-content-center" style="margin-top: 3%;">


                <div class="col-lg-7 px-lg-3 pt-4 card" style="style= border: 1xp; border-color: #667b68;">
                    <div>
                        <div class="container">

                            <div class="form-horizontal">
                                <h2 style="color: ;">Eliminar prueba</h2>
                            </div>
                            <hr />

                            <table class="table table-striped table-bordered" style="background-color: #D2DCCD; width: 93%; margin-left: 2%; margin-top: 4%">
                                <thead class="thead-light">
                                    <tr class="text-center">
                                        <th>Nombre</th>
                                        <th>Duración</th>
                                        <th>Instrucciones</th>
                                        <th>Tipo de Prueba</th>
                                    </tr>
                                </thead>

                                <tr class="text-center">
                                    <td>
                                        @Html.DisplayFor(model => model.name, new { @class = "form-control" })
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.duration, new { @class = "form-control" })
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.instructions, new { @class = "form-control" })
                                    </td>
                                    <td>
                                        @ViewBag.testType
                                    </td>
                                </tr>

                            </table>

                            <div class="form-group pb-3" style="margin-top:7%">
                                <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Index","VirtualTest")">Regresar</a>
                                <input style=" margin-left: " type="submit" value="Eliminar" class="btn btn-outline-danger" />
                            </div>

                        </div>

                    </div>

                </div>
            </div>

        </div>
    }

</body>
</html>

App_OL2022/Views/VirtualTest/Edit.cshtml
@model mysqltest.Models.virtual_tests

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Editar</title>
    <link href="~/css/homeCss/home.css" rel="stylesheet" />
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link href="~/css/styleguide.css" rel="stylesheet" />
    <link href="~/css/globals.css" rel="stylesheet" />
    <link href="~/css/css-boots/bootstrap.css" rel="stylesheet" />
</head>
<body style="background-color: #ffffff;">

    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        <div class="row justify-content-center" style="margin-top: 3%;">

            <div class="col-lg-3 px-lg-3 pt-4 card" style="style= border: 1xp; border-color: #667b68;">
                <div class="container">

                    <div>
                        <div class="form-horizontal">
                            <h2 style="color: ;">Editar prueba</h2>

                            <p style="color: #EAD1C5;">@ViewBag.Error</p>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger text-dark" })
                            @Html.HiddenFor(model => model.virtual_test_id)

                            @Html.ValidationSummary(true, "", new { @class = "text-danger text-dark" })
                            <div class="form-group">
                                <h3 class="control-label col-md-12">Nombre</h3>
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control text-dark" } })
                                    @Html.ValidationMessageFor(model => model.name, "", new { @style = "color: #EAD1C5" })
                                </div>
                            </div>

                            <div class="form-group">
                                <h3 class="control-label col-md-12">Duración</h3>
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.duration, new { htmlAttributes = new { @class = "form-control text-dark" } })
                                    @Html.ValidationMessageFor(model => model.duration, "", new { @style = "color: #EAD1C5" })
                                </div>
                            </div>

                            <div class="form-group">
                                <h3 class="control-label col-md-12">Instrucciones</h3>
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.instructions, new { htmlAttributes = new { @class = "form-control text-dark" } })
                                    @Html.ValidationMessageFor(model => model.instructions, "", new { @style = "color: #EAD1C5" })
                                </div>
                            </div>

                            <div class="form-group">
                                <h3 class="control-label col-md-12">Tipo</h3>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(model => model.type, new SelectList(ViewBag.testType, "test_type_id", "name"), new { @class = "form-control text-dark" })
                                    @Html.ValidationMessageFor(model => model.type, "", new { @style = "color: #EAD1C5" })
                                </div>
                            </div>

                            <div class="form-group pb-3">
                                <div class="col-md-offset-12 col-md-12" style="margin-top:7%">
                                    <a style=" margin-left: 2%" class="main_nav_item btn btn-outline-dark" href="@Url.Action("Index","VirtualTest")">Regresar</a>
                                    <input style=" margin-left: " type="submit" value="Editar" class="btn btn-outline-dark" />
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    }

</body>
</html>

App_OL2022/Views/VirtualTest/Index.cshtml
@*@model IEnumerable<mysqltest.Models.virtual_tests>*@

@using mysqltest.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<virtual_tests>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Cursos</title>
    <link rel="stylesheet" type="text/css" href="~/css/Cruds/crud-general2.css" />
    <link rel="stylesheet" type="text/css" href="~/css/styleguide.css" />
    <link rel="stylesheet" type="text/css" href="~/css/globals.css" />
    <link href="~/css/Pagination.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/css/css-boots/bootstrap.css" />
    <style>
        .pagination {
            display: inline-block;
            padding-left: 0;
            margin: 20px 0;
            border-radius: 4px;
        }

            .pagination > li {
                display: inline;
            }

                .pagination > li > a,
                .pagination > li > span {
                    position: relative;
                    float: left;
                    padding: 6px 12px;
                    margin-left: -1px;
                    line-height: 1.428571429;
                    text-decoration: none;
                    background-color: #ffffff;
                    border: 1px solid #dddddd;
                }

                .pagination > li:first-child > a,
                .pagination > li:first-child > span {
                    margin-left: 0;
                    border-bottom-left-radius: 4px;
                    border-top-left-radius: 4px;
                }

                .pagination > li:last-child > a,
                .pagination > li:last-child > span {
                    border-top-right-radius: 4px;
                    border-bottom-right-radius: 4px;
                }

                .pagination > li > a:hover,
                .pagination > li > span:hover,
                .pagination > li > a:focus,
                .pagination > li > span:focus {
                    background-color: #eeeeee;
                }

            .pagination > .active > a,
            .pagination > .active > span,
            .pagination > .active > a:hover,
            .pagination > .active > span:hover,
            .pagination > .active > a:focus,
            .pagination > .active > span:focus {
                z-index: 2;
                color: #ffffff;
                cursor: default;
                background-color: #428bca;
                border-color: #428bca;
            }

            .pagination > .disabled > span,
            .pagination > .disabled > a,
            .pagination > .disabled > a:hover,
            .pagination > .disabled > a:focus {
                color: #999999;
                cursor: not-allowed;
                background-color: #ffffff;
                border-color: #dddddd;
            }

        .pagination-lg > li > a,
        .pagination-lg > li > span {
            padding: 10px 16px;
            font-size: 18px;
        }

        .pagination-lg > li:first-child > a,
        .pagination-lg > li:first-child > span {
            border-bottom-left-radius: 6px;
            border-top-left-radius: 6px;
        }

        .pagination-lg > li:last-child > a,
        .pagination-lg > li:last-child > span {
            border-top-right-radius: 6px;
            border-bottom-right-radius: 6px;
        }

        .pagination-sm > li > a,
        .pagination-sm > li > span {
            padding: 5px 10px;
            font-size: 12px;
        }

        .pagination-sm > li:first-child > a,
        .pagination-sm > li:first-child > span {
            border-bottom-left-radius: 3px;
            border-top-left-radius: 3px;
        }

        .pagination-sm > li:last-child > a,
        .pagination-sm > li:last-child > span {
            border-top-right-radius: 3px;
            border-bottom-right-radius: 3px;
        }

        .pager {
            padding-left: 0;
            margin: 20px 0;
            text-align: center;
            list-style: none;
        }

            .pager:before,
            .pager:after {
                display: table;
                content: " ";
            }

            .pager:after {
                clear: both;
            }

            .pager:before,
            .pager:after {
                display: table;
                content: " ";
            }

            .pager:after {
                clear: both;
            }

            .pager li {
                display: inline;
            }

                .pager li > a,
                .pager li > span {
                    display: inline-block;
                    padding: 5px 14px;
                    background-color: #ffffff;
                    border: 1px solid #dddddd;
                    border-radius: 15px;
                }

                    .pager li > a:hover,
                    .pager li > a:focus {
                        text-decoration: none;
                        background-color: #eeeeee;
                    }

            .pager .next > a,
            .pager .next > span {
                float: right;
            }

            .pager .previous > a,
            .pager .previous > span {
                float: left;
            }

            .pager .disabled > a,
            .pager .disabled > a:hover,
            .pager .disabled > a:focus,
            .pager .disabled > span {
                color: #999999;
                cursor: not-allowed;
                background-color: #ffffff;
            }

        .pagination-container {
            text-align: center;
        }
    </style>
</head>

<body style="margin: 0; background: #ffffff">
    <input type="hidden" id="anPageName" name="page" value="crud-general2" />
    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">
                    <a href="@Url.Action("Index", "Admin")">
                        <div class="inicio">Administración</div>
                    </a>
                    <a href="@Url.Action("Index","TestType")">
                        <div class="registrarse">Tipo de Pruebas</div>
                    </a>
                    <a href="@Url.Action("Index","Questions")">
                        <div class="iniciar-sesin">Preguntas</div>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <h2 style="color: #677C78; margin-top: 2%;" class="text-center">ADMINISTRACIÓN DE PRUEBAS VIRTUALES</h2>

    <div class="row g-0" style="margin-top:2%; margin-left:4%;">

        <div class="col-md-9">
            <a class="btn btn-outline-dark" href="@Url.Action("Index", "Admin")">Regresar</a>
            @if (ViewBag.role == 1)
            {
                <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Create","VirtualTest")">Crear Nueva Prueba</a>

            }
        </div>

        <div class="col-md-3">

            <form class="form-inline my-2 my-lg-0 " style="margin: 10%; padding: 5%;">
                <input class="form-control mr-sm-2 text-dark" type="text" id="search" placeholder="Buscar" onkeyup="myFunction()">

            </form>
        </div>

    </div>


    <script>
        function myFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("search");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>

    <div style=" width: 95%; margin-left: 3%;">

        <table class="table table-hover" id="myTable">
            <thead class="table-dark">
                <tr class="text-center">
                    <th>Nombre</th>
                    <th>Duración (Min)</th>
                    <th>Instrucciones</th>
                    <th>Tipo</th>
                    <th colspan="5">Acciones</th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr class="text-center">
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.duration)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.instructions)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.test_type.name)
                    </td>
                    @if (ViewBag.role == 1)
                    {
                        <td>
                            <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Edit","VirtualTest", new { id = item.virtual_test_id })">Editar</a>
                        </td>
                        <td>
                            <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Delete","VirtualTest", new { id = item.virtual_test_id })">Eliminar</a>
                        </td>
                        <td>
                            <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("AsignQuestionToTest","Admin", new { id = item.virtual_test_id })">Agregar Pregunta</a>
                        </td>
                    }
                    <td>
                        <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("QuestionsAssignedInd","Admin", new { id = item.virtual_test_id })">Preguntas Agregadas</a>
                    </td>

                    <td>
                        <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Solved","Admin", new { id = item.virtual_test_id, qvt_id = 0 })">Realizar Prueba</a>
                    </td>

                </tr>
            }

        </table>
    </div>

    <div class="row g-0" style="padding: 1%;">
        <div class="col-md-6">
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
        </div>
        <div class="col-md-6">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
        </div>
    </div>

   

</body>

</html>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>