App_OL2022/Models/questions.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysqltest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public questions()
        {
            this.question_vt = new HashSet<question_vt>();
            this.answer_vt = new HashSet<answer_vt>();
        }
        public int question_id { get; set; }
        [Required(ErrorMessage = "* Ingrese la pregunta de la prueba")]
        [Display(Name = "Pregunta")]
        [StringLength(800, MinimumLength = 10)]
        public string question { get; set; }


        [Required(ErrorMessage = "* Ingrese la respuesta 1 de la prueba")]
        [Display(Name = "Respuesta")]
        [StringLength(800, MinimumLength = 1)]
        public string answer1 { get; set; }


        [Required(ErrorMessage = "* Ingrese la respuesta 2 de la prueba")]
        [Display(Name = "Respuesta")]
        [StringLength(800, MinimumLength = 1)]
        public string answer2 { get; set; }


        [Required(ErrorMessage = "* Ingrese la respuesta 3 de la prueba")]
        [Display(Name = "Respuesta")]
        [StringLength(800, MinimumLength = 1)]
        public string answer3 { get; set; }


        [Required(ErrorMessage = "* Ingrese la respuesta 4 de la prueba")]
        [Display(Name = "Respuesta")]
        [StringLength(800, MinimumLength = 1)]
        public string answer4 { get; set; }
        public int correct_answer { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question_vt> question_vt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<answer_vt> answer_vt { get; set; }
    }
}

App_OL2022/Controllers/QuestionsController.cs
using mysqltest.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mysqltest.Controllers
{
    public class QuestionsController : Controller
    {
        owldbEntities01 owldb = new owldbEntities01();
        RoleSearching rs = new RoleSearching();
        // GET: Module
        public ActionResult Index(int? page)
        {
            if (Request.IsAuthenticated)
            {
                ViewBag.role = rs.GetRole(this.HttpContext.User.Identity.Name);
            }

            var pageNumber = page ?? 1;
            var pageSize = 10;
            var query = owldb.questions.OrderBy(a => a.question).ToPagedList(pageNumber, pageSize);

            return View(query);
        }

        // GET: Module/Create
        public ActionResult Create()
        {
            List<int> answers = new List<int>();
            answers.Add(1);
            answers.Add(2);
            answers.Add(3);
            answers.Add(4);

            ViewBag.ans = answers;
            return View();
        }

        // POST: Module/Create
        [HttpPost]
        public ActionResult Create(questions q)
        {
            var query = owldb.questions.Where(x => x.question == q.question).FirstOrDefault();

            try
            {
                if (query == null)
                {
                    owldb.questions.Add(q);
                    owldb.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    List<int> answers = new List<int>
                    {
                        1,
                        2,
                        3,
                        4
                    };

                    ViewBag.Error = "* Pregunta Existente.";
                    ViewBag.ans = answers;
                    return View(q);
                }

                
            }
            catch (DbEntityValidationException dbEx)
            {

                List<int> answers = new List<int>
                {
                    1,
                    2,
                    3,
                    4
                };

                ViewBag.ans = answers;
                return View(q);
            }
        }


        // GET: Module/Edit/5
        public ActionResult Edit(int id)
        {
            List<int> answers = new List<int>();
            answers.Add(1);
            answers.Add(2);
            answers.Add(3);
            answers.Add(4);

            ViewBag.ans = answers;
            questions q = new questions();
            q = owldb.questions.Where(x => x.question_id == id).FirstOrDefault();

            return View(q);
        }

        // POST: Module/Edit/5
        [HttpPost]
        public ActionResult Edit(questions q)
        {
            var query = owldb.questions.Where(x => x.question_id != q.question_id && x.question == q.question).FirstOrDefault();

            try
            {
                if (query==null || query!=null && query.question_id == q.question_id)
                {
                    questions qst = owldb.questions.Single(w => w.question_id == q.question_id);
                    qst.question = q.question;
                    qst.answer1 = q.answer1;
                    qst.answer2 = q.answer2;
                    qst.answer3 = q.answer3;
                    qst.answer4 = q.answer4;

                    owldb.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    List<int> answers = new List<int>();
                    answers.Add(1);
                    answers.Add(2);
                    answers.Add(3);
                    answers.Add(4);

                    ViewBag.ans = answers;
                    ViewBag.Error = "* Pregunta Ya Existe.";
                    return View();
                }

                
            }
            catch (Exception e)
            {
                List<int> answers = new List<int>();
                answers.Add(1);
                answers.Add(2);
                answers.Add(3);
                answers.Add(4);

                ViewBag.ans = answers;
                return View();
            }
        }

        // GET: Module/Delete/5
        public ActionResult Delete(int id, string q)
        {
            var query = owldb.questions.Where(a => a.question_id == id).FirstOrDefault();
            questions qst = new questions();
            qst.question = query.question;
            qst.answer1 = query.answer1;
            qst.answer2 = query.answer2;
            qst.answer3 = query.answer3;
            qst.answer4 = query.answer4;

            return View(qst);
        }

        // POST: Module/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var query = owldb.questions.Where(a => a.question_id == id).FirstOrDefault();
                owldb.questions.Remove(query);
                owldb.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

App_OL2022/Views/Questions/Create.cshtml
@model mysqltest.Models.questions

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Crear</title>
    <link href="~/css/homeCss/home.css" rel="stylesheet" />
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link href="~/css/styleguide.css" rel="stylesheet" />
    <link href="~/css/globals.css" rel="stylesheet" />
    <link href="~/css/css-boots/bootstrap.css" rel="stylesheet" />
</head>
<body style="background-color: #ffffff;">

    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                    
                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="row justify-content-center" style="margin-top: 3%;">


    <div class="col-lg-5 px-lg-3 pt-4 card" style="style= border: 1xp; border-color: #667b68;">
        <div class="container">

            <div class="form-horizontal">
                <h2 style="color: ;">Crear Nueva Pregunta</h2>
                <p style="color: red;">@ViewBag.Error</p>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <h3 class="control-label col-md-auto">Pregunta</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.question, new { htmlAttributes = new { @class = "form-control text-dark" } })
                        @Html.ValidationMessageFor(model => model.question, "", new { @style = "color: #EAD1C5" })
                    </div>
                    <h3 class="control-label col-md-auto">Respuesta 1</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.answer1, new { htmlAttributes = new { @class = "form-control text-dark" } })
                        @Html.ValidationMessageFor(model => model.answer1, "", new { @style = "color: #EAD1C5" })
                    </div>
                    <h3 class="control-label col-md-auto">Respuesta 2</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.answer2, new { htmlAttributes = new { @class = "form-control text-dark" } })
                        @Html.ValidationMessageFor(model => model.answer2, "", new { @style = "color: #EAD1C5" })
                    </div>
                    <h3 class="control-label col-md-auto">Respuesta 3</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.answer3, new { htmlAttributes = new { @class = "form-control text-dark" } })
                        @Html.ValidationMessageFor(model => model.answer3, "", new { @style = "color: #EAD1C5" })
                    </div>
                    <h3 class="control-label col-md-auto">Respuesta 4</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.answer4, new { htmlAttributes = new { @class = "form-control text-dark" } })
                        @Html.ValidationMessageFor(model => model.answer4, "", new { @style = "color: #EAD1C5" })
                    </div>
                    <h3 class="control-label col-md-auto">Respuesta Correcta</h3>
                    <div class="col-md-12">
                        @Html.DropDownListFor(model => model.correct_answer, new SelectList(ViewBag.ans), new { @class = "form-control text-dark" })
                        @Html.ValidationMessageFor(model => model.correct_answer, "", new { @style = "color: #EAD1C5" })
                    </div>
                </div>
                 
                <div class="form-group pb-3">
                    <div class="col-md-offset-2 col-md-10" style="margin-top:7%">
                        <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Index","Questions")">Regresar </a>
                        <input type="submit" value="Crear" class="main_nav_item btn btn-outline-dark" />

                    </div>
                </div>


            </div>
        </div>

    </div>
</div>

    }

</body>
</html>

App_OL2022/Views/Questions/Delete.cshtml
@model mysqltest.Models.questions
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Eliminar</title>
    <link href="~/css/homeCss/home.css" rel="stylesheet" />
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link href="~/css/styleguide.css" rel="stylesheet" />
    <link href="~/css/globals.css" rel="stylesheet" />
    <link href="~/css/css-boots/bootstrap.css" rel="stylesheet" />
</head>
<body style="background-color: #ffffff;">

    <div class=" row justify-content-center">
        <div class=" col-lg-8 crud-general2 screen ">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                   
                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.question_id)

        <div class="form-actions no-color">

            <div class="row justify-content-center" style="margin-top: 3%;">


                <div class="col-lg-8 px-lg-3 pt-4 card" style=" border: ; border-color: #667b68;">
                    <div class="container">

                        <div class="form-horizontal">
                            <h2 style="color: ;">Eliminar pregunta</h2>
                        </div>
                        <hr />

                        <table class="table table-striped table-bordered " style="background-color: #D2DCCD;  margin-top: 4% ">
                            <thead class="thead-light">
                                <tr class="text-center">
                                    <th>Pregunta</th>
                                    <th>Respuesta 1</th>
                                    <th>Respuesta 2</th>
                                    <th>Respuesta 3</th>
                                    <th>Respuesta 4</th>
                                    <th>Respuesta Correcta</th>
                                </tr>
                            </thead>

                            <tr class="text-center">
                                <td>
                                    @Html.DisplayFor(model => model.question, new { @class = "form-control" })
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.answer1, new { @class = "form-control" })
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.answer2, new { @class = "form-control" })
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.answer3, new { @class = "form-control" })
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.answer4, new { @class = "form-control" })
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.correct_answer, new { @class = "form-control" })
                                </td>
                            </tr>

                        </table>

                        <div class="form-group pb-3" style="margin-top:7%">
                            <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Index","Questions")">Regresar</a>
                            <input style=" margin-left: " type="submit" value="Eliminar" class="btn btn-outline-danger" />
                        </div>

                    </div>

                </div>
            </div>

        </div>
    }


</body>
</html>

App_OL2022/Views/Questions/Edit.cshtml
@model mysqltest.Models.questions

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Editar</title>
    <link href="~/css/homeCss/home.css" rel="stylesheet" />
    <link href="~/css/Cruds/crud-general2.css" rel="stylesheet" />
    <link href="~/css/styleguide.css" rel="stylesheet" />
    <link href="~/css/globals.css" rel="stylesheet" />
    <link href="~/css/css-boots/bootstrap.css" rel="stylesheet" />
</head>
<body style="background-color: #ffffff;">

    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">

                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="row justify-content-center" style="margin-top: 3%;">


            <div class="col-lg-4 px-lg-3 pt-4 card" style="style= border: 1xp; border-color: #667b68;">
                <div class="container">

                    <div class="form-horizontal">
                        <h2 style="color: ;">Editar preguntas</h2>
                        <p style="color: red;">@ViewBag.Error</p>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.question_id)

                        <h3 class="control-label col-md-auto">Pregunta</h3>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.question, new { htmlAttributes = new { @class = "form-control text-dark" } })
                            @Html.ValidationMessageFor(model => model.question, "", new { @style = "color: #EAD1C5" })
                        </div>
                        <h3 class="control-label col-md-auto">Respuesta 1</h3>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.answer1, new { htmlAttributes = new { @class = "form-control text-dark" } })
                            @Html.ValidationMessageFor(model => model.answer1, "", new { @style = "color: #EAD1C5" })
                        </div>
                        <h3 class="control-label col-md-auto">Respuesta 2</h3>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.answer2, new { htmlAttributes = new { @class = "form-control text-dark" } })
                            @Html.ValidationMessageFor(model => model.answer2, "", new { @style = "color: #EAD1C5" })
                        </div>
                        <h3 class="control-label col-md-auto">Respuesta 3</h3>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.answer3, new { htmlAttributes = new { @class = "form-control text-dark" } })
                            @Html.ValidationMessageFor(model => model.answer3, "", new { @style = "color: #EAD1C5" })
                        </div>
                        <h3 class="control-label col-md-auto">Respuesta 4</h3>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.answer4, new { htmlAttributes = new { @class = "form-control text-dark" } })
                            @Html.ValidationMessageFor(model => model.answer4, "", new { @style = "color: #EAD1C5" })
                        </div>
                        <h3 class="control-label col-md-auto">Respuesta Correcta</h3>
                        <div class="col-md-12">
                            @Html.DropDownListFor(model => model.correct_answer, new SelectList(ViewBag.ans), new { @class = "form-control  text-dark" })
                            @Html.ValidationMessageFor(model => model.correct_answer, "", new { @style = "color: #EAD1C5" })
                        </div>

                        <div class="form-group pb-3">
                            <div class="col-md-offset-2 col-md-10" style="margin-top:7%">
                                <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Index","Questions")">Regresar</a>
                                <input type="submit" value="Editar" class="btn btn-outline-dark" />
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    }

</body>
</html>

App_OL2022/Views/Questions/Index.cshtml
@*@model IEnumerable<mysqltest.Models.questions>*@

@using mysqltest.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<questions>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Preguntas</title>
    <link rel="stylesheet" type="text/css" href="~/css/Cruds/crud-general2.css" />
    <link rel="stylesheet" type="text/css" href="~/css/styleguide.css" />
    <link rel="stylesheet" type="text/css" href="~/css/globals.css" />
    <link href="~/css/Pagination.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/css/css-boots/bootstrap.css" />


    <style>
        table.dataTable thead .sorting:after,
        table.dataTable thead .sorting:before,
        table.dataTable thead .sorting_asc:after,
        table.dataTable thead .sorting_asc:before,
        table.dataTable thead .sorting_asc_disabled:after,
        table.dataTable thead .sorting_asc_disabled:before,
        table.dataTable thead .sorting_desc:after,
        table.dataTable thead .sorting_desc:before,
        table.dataTable thead .sorting_desc_disabled:after,
        table.dataTable thead .sorting_desc_disabled:before {
            bottom: .5em;
        }

        .myclass:hover {
            color: white;
        }
    </style>


    <script>
        $(document).ready(function () {
            $('#dtBasicExample').DataTable();
            $('.dataTables_length').addClass('bs-select');
        });

        $(document).ready(function () {
            $('#dtBasicExample').DataTable({
                "searching": false // false to disable search (or any other option)
            });
            $('.dataTables_length').addClass('bs-select');
        });
    </script>

    <script>
        function myFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("search");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
</head>

<body style="margin: 0; background: #ffffff">
    <input type="hidden" id="anPageName" name="page" value="crud-general2" />
    <div class="container-center-horizontal">
        <div class="crud-general2 screen">

            <div class="grupo-20">

                <div class="layout segoeui-regular-normal-ebb-22px">
                    <a href="@Url.Action("Index", "Admin")">
                        <div class="inicio">Administraci&oacute;n</div>
                    </a>
                    <a href="@Url.Action("Index","VirtualTest")">
                        <div class="registrarse">Pruebas</div>
                    </a>
                    <a href="@Url.Action("Index","TestType")">
                        <div class="registrarse">Tipo de Pruebas</div>
                    </a>

                </div>
            </div>
        </div>
    </div>

    <h2 style="color: #677C78; margin-top: 2%;" class="text-center">ADMINISTRACIÓN DE PREGUNTAS</h2>

    <div class="row g-0" style="margin-top:2%; margin-left:4%;">

        <div class="col-md-9">
            <a class="btn btn-outline-dark" href="@Url.Action("Index","VirtualTest")">Volver a Pruebas Virtuales</a>
            @if (ViewBag.role == 1)
            {
                <a class="main_nav_item btn btn-outline-dark" href="@Url.Action("Create", "Questions")">Crear Nueva Pregunta</a>
            }
        </div>
        <div class="col-md-3">

            <form class="form-inline my-2 my-lg-0 " style="margin: 10%; padding: 5%;">
                <input class="form-control mr-sm-2 text-dark" type="text" id="search" placeholder="Buscar" onkeyup="myFunction()">

            </form>
        </div>

    </div>

    <div style=" width: 95%; margin-left: 3%;">

        <table class="table table-hover" id="myTable">
            <thead class="table-dark">
                <tr class="text-center">
                    <th>Pregunta</th>
                    <th>Respuesta 1</th>
                    <th>Respuesta 2</th>
                    <th>Respuesta 3</th>
                    <th>Respuesta 4</th>
                    <th>Respuesta Correcta</th>
                    @if (ViewBag.role == 1)
                    {
                        <th colspan="2">
                            Acciones
                        </th>

                    }
                    else
                    {
                        <th>
                            Acciones
                        </th>

                    }


                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr class="text-center">
                    <td>
                        @Html.DisplayFor(modelItem => item.question)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.answer1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.answer2)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.answer3)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.answer4)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.correct_answer)
                    </td>
                    @if (ViewBag.role == 1)
                    {
                        <td>
                            <a class="btn btn-outline-dark" href="@Url.Action("Delete","Questions", new { id = item.question_id })">Eliminar</a>
                        </td>
                    }
                    <td>
                        <a class="btn btn-outline-dark" href="@Url.Action("Edit","Questions", new { id = item.question_id })">Editar</a>
                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="row g-0" style="padding: 1%;">
        <div class="col-md-6">
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
        </div>
        <div class="col-md-6">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
        </div>
    </div>

</body>
</html>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>